name: CMake build
description: CMake Composite Action

inputs:
  buildType:
    required: true
    description: Debug or Release

  runTests:
    required: false
    description: Run 'gradle check'

  keystore:
    required: true
    description: signing keystore

  keystorePassword:
    required: true
    description: signing keystore password

runs:
  using: "composite"
  steps:
    - name: install contemporary cmake
      uses: lukka/get-cmake@v3.30.1

    - uses: actions/download-artifact@v4
      with:
        pattern: dependencies-*
        merge-multiple: true
        path: tunnel/build/cmake/

    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin
        cache: gradle

    - name: Setup keystore
      shell: bash
      run: |
        echo "${{ inputs.keystore }}" | base64 -d > ${{ runner.workspace }}/ziti-mobile.jks

    - name: Build Android ${{ inputs.buildType }} Bundle
      shell: bash
      run: |
        ls -l tunnel/build/cmake/
        ./gradlew -PskipDependentBuild assemble${{ inputs.buildType }} bundle${{ inputs.buildType }}
      env:
        RELEASE_KEYSTORE: ${{ runner.workspace }}/ziti-mobile.jks
        RELEASE_KEYSTORE_PASSWORD: ${{ inputs.keystorePassword }}
