name: build and cache native dependencies

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-deps:
    runs-on: ubuntu-latest
    name: build dependencies[${{ matrix.target }}]
    strategy:
      matrix:
        target:
          - arm-android
          - arm64-android
          - x64-android
          - x86-android
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: setup build
        shell: bash
        run: |
          CI_CACHE=${GITHUB_WORKSPACE}/_ci_cache
          VCPKG_BINARY_SOURCES="clear;files,${CI_CACHE},readwrite"
          mkdir -p ${CI_CACHE}
          echo "CI_CACHE=${CI_CACHE}" >> ${GITHUB_ENV}
          echo "VCPKG_BINARY_SOURCES=${VCPKG_BINARY_SOURCES}" >> ${GITHUB_ENV}

      - name: Cache ${{ matrix.target }} dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ env.CI_CACHE }}
          key: dep-${{ matrix.target }}-${{ hashFiles('./tunnel/vcpkg.json') }}
          restore-keys: |
            dep-${{ matrix.target }}-

      - name: build dependencies
        uses: ./.github/actions/dependencies
        with:
          target: ${{ matrix.target }}

      - name: upload cache artifact
        uses: actions/upload-artifact@v4
        with:
          path: tunnel/build/cmake
          name: dependencies-${{ matrix.target }}
