name: Publish Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-deps:
    uses: ./.github/workflows/build-dependencies.yml
  build:
    runs-on: ubuntu-latest
    needs:
      - build-deps
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup build
        shell: bash
        run: |
          CI_CACHE=${GITHUB_WORKSPACE}/.ci_cache
          VCPKG_BINARY_SOURCES="clear;files,${GITHUB_WORKSPACE}/.ci_cache,readwrite"
          mkdir -p ${CI_CACHE}
          echo "CI_CACHE=${CI_CACHE}" >> ${GITHUB_ENV}
          echo "VCPKG_BINARY_SOURCES=${VCPKG_BINARY_SOURCES}" >> ${GITHUB_ENV}

      - name: Build App
        uses: ./.github/actions/gradle
        with:
          buildType: Release
          keystore: ${{ secrets.RELEASE_KEYSTORE }}
          keystorePassword: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}

      - name: Upload Release artifacts
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: |
            app/build/outputs/bundle/release/*.aab
            app/build/outputs/apk/release/*.apk
